apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "task-app.fullname" . }}-config
  namespace: {{ .Values.namespaces.backend }}
data:
  LOG_LEVEL: {{ .Values.config.LOG_LEVEL | quote }}
  DB_TIMEOUT: {{ .Values.config.DB_TIMEOUT | quote }}

---
# Backend database credentials secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-app.fullname" . }}-db
  namespace: {{ .Values.namespaces.backend }}
type: Opaque
stringData:
  database: {{ .Values.postgresql.auth.database | quote }}
  username: {{ .Values.postgresql.auth.username | quote }}
  password: {{ .Values.postgresql.auth.password | quote }}

---
# Database credentials secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-app.fullname" . }}-db
  namespace: {{ .Values.namespaces.database }}
type: Opaque
stringData:
  database: {{ .Values.postgresql.auth.database | quote }}
  username: {{ .Values.postgresql.auth.username | quote }}
  password: {{ .Values.postgresql.auth.password | quote }}

