---
# Frontend Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.frontend }}
  labels:
    name: {{ .Values.namespaces.frontend }}
    app: {{ include "task-app.name" . }}
    chart: {{ include "task-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

---
# Backend Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.backend }}
  labels:
    name: {{ .Values.namespaces.backend }}
    app: {{ include "task-app.name" . }}
    chart: {{ include "task-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

---
# Database Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.database }}
  labels:
    name: {{ .Values.namespaces.database }}
    app: {{ include "task-app.name" . }}
    chart: {{ include "task-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
