{{- if and .Values.dockerRegistry (ne .Values.dockerRegistry.username "") (ne .Values.dockerRegistry.password "") }}
{{- $auth := printf "%s:%s" .Values.dockerRegistry.username .Values.dockerRegistry.password | b64enc }}
{{- $dockerConfig := printf "{\"auths\":{\"docker.io\":{\"auth\":\"%s\"}}}" $auth | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-secret
  namespace: {{ .Values.namespaces.backend }}
type: kubernetes.io/dockercfg
data:
  .dockercfg: {{ $dockerConfig | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-secret
  namespace: {{ .Values.namespaces.frontend }}
type: kubernetes.io/dockercfg
data:
  .dockercfg: {{ $dockerConfig | quote }}
{{- end }}
