apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-secret
  namespace: {{ .Values.namespaces.backend }}
type: kubernetes.io/dockercfg
data:
  .dockercfg: {{ include "task-app.dockerConfig" . | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-secret
  namespace: {{ .Values.namespaces.frontend }}
type: kubernetes.io/dockercfg
data:
  .dockercfg: {{ include "task-app.dockerConfig" . | b64enc | quote }}
{{- end }}
